#!/usr/bin/env bash

# Check if exactly 4 arguments are provided
if ["$#" -ne 4]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1

fi

# ASSIGN arguments to variables for clarity
FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer the file to the user's home directory
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$SERVER_IP:~/"
